ALTER TABLE skill_sheets
  ADD COLUMN IF NOT EXISTS birth_date DATE,
  ADD COLUMN IF NOT EXISTS nationality VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS station_line VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS nearest_station VARCHAR(100) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS desired_area VARCHAR(255) NOT NULL DEFAULT '';
